root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/logidoc-server ./cmd/server"
  bin = "./tmp/logidoc-server"
  full_bin = "./tmp/logidoc-server"
  include_ext = ["go", "toml", "env"]
  exclude_dir = ["tmp", "vendor", "testutil", "research", "fern", "api"]
  exclude_regex = ["_test\\.go$"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
