services:
  logidoc:
    build: .
    ports:
      - "7042:7042"
      - "7043:7043"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      mongo:
        condition: service_started

  mongo:
    image: mongo:7
    ports:
      - "27042:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
